// import Head from 'next/head'
import {Heading} from "@chakra-ui/react";

// const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      {/*<Head>*/}
      {/*  <title>Create Next App</title>*/}
      {/*  <meta name="description" content="Generated by create next app" />*/}
      {/*  <meta name="viewport" content="width=device-width, initial-scale=1" />*/}
      {/*  <link rel="icon" href="/favicon.ico" />*/}
      {/*</Head>*/}

      <Heading as='h1' size='lg' lineHeight={1.5}>Home</Heading>
    </>
  )
}
